// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// V2UpdateHostMediaPreloadStatusHandlerFunc turns a function with the right signature into a v2 update host media preload status handler
type V2UpdateHostMediaPreloadStatusHandlerFunc func(V2UpdateHostMediaPreloadStatusParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn V2UpdateHostMediaPreloadStatusHandlerFunc) Handle(params V2UpdateHostMediaPreloadStatusParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// V2UpdateHostMediaPreloadStatusHandler interface for that can handle valid v2 update host media preload status params
type V2UpdateHostMediaPreloadStatusHandler interface {
	Handle(V2UpdateHostMediaPreloadStatusParams, interface{}) middleware.Responder
}

// NewV2UpdateHostMediaPreloadStatus creates a new http.Handler for the v2 update host media preload status operation
func NewV2UpdateHostMediaPreloadStatus(ctx *middleware.Context, handler V2UpdateHostMediaPreloadStatusHandler) *V2UpdateHostMediaPreloadStatus {
	return &V2UpdateHostMediaPreloadStatus{Context: ctx, Handler: handler}
}

/* V2UpdateHostMediaPreloadStatus swagger:route PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status installer v2UpdateHostMediaPreloadStatus

Update media preload status.

*/
type V2UpdateHostMediaPreloadStatus struct {
	Context *middleware.Context
	Handler V2UpdateHostMediaPreloadStatusHandler
}

func (o *V2UpdateHostMediaPreloadStatus) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewV2UpdateHostMediaPreloadStatusParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
