// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/openshift/assisted-service/models"
)

// V2UpdateHostMediaPreloadStatusNoContentCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusNoContent
const V2UpdateHostMediaPreloadStatusNoContentCode int = 204

/*V2UpdateHostMediaPreloadStatusNoContent Update received

swagger:response v2UpdateHostMediaPreloadStatusNoContent
*/
type V2UpdateHostMediaPreloadStatusNoContent struct {
}

// NewV2UpdateHostMediaPreloadStatusNoContent creates V2UpdateHostMediaPreloadStatusNoContent with default headers values
func NewV2UpdateHostMediaPreloadStatusNoContent() *V2UpdateHostMediaPreloadStatusNoContent {

	return &V2UpdateHostMediaPreloadStatusNoContent{}
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// V2UpdateHostMediaPreloadStatusUnauthorizedCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusUnauthorized
const V2UpdateHostMediaPreloadStatusUnauthorizedCode int = 401

/*V2UpdateHostMediaPreloadStatusUnauthorized Unauthorized.

swagger:response v2UpdateHostMediaPreloadStatusUnauthorized
*/
type V2UpdateHostMediaPreloadStatusUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusUnauthorized creates V2UpdateHostMediaPreloadStatusUnauthorized with default headers values
func NewV2UpdateHostMediaPreloadStatusUnauthorized() *V2UpdateHostMediaPreloadStatusUnauthorized {

	return &V2UpdateHostMediaPreloadStatusUnauthorized{}
}

// WithPayload adds the payload to the v2 update host media preload status unauthorized response
func (o *V2UpdateHostMediaPreloadStatusUnauthorized) WithPayload(payload *models.InfraError) *V2UpdateHostMediaPreloadStatusUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status unauthorized response
func (o *V2UpdateHostMediaPreloadStatusUnauthorized) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateHostMediaPreloadStatusForbiddenCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusForbidden
const V2UpdateHostMediaPreloadStatusForbiddenCode int = 403

/*V2UpdateHostMediaPreloadStatusForbidden Forbidden.

swagger:response v2UpdateHostMediaPreloadStatusForbidden
*/
type V2UpdateHostMediaPreloadStatusForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.InfraError `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusForbidden creates V2UpdateHostMediaPreloadStatusForbidden with default headers values
func NewV2UpdateHostMediaPreloadStatusForbidden() *V2UpdateHostMediaPreloadStatusForbidden {

	return &V2UpdateHostMediaPreloadStatusForbidden{}
}

// WithPayload adds the payload to the v2 update host media preload status forbidden response
func (o *V2UpdateHostMediaPreloadStatusForbidden) WithPayload(payload *models.InfraError) *V2UpdateHostMediaPreloadStatusForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status forbidden response
func (o *V2UpdateHostMediaPreloadStatusForbidden) SetPayload(payload *models.InfraError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateHostMediaPreloadStatusNotFoundCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusNotFound
const V2UpdateHostMediaPreloadStatusNotFoundCode int = 404

/*V2UpdateHostMediaPreloadStatusNotFound Error.

swagger:response v2UpdateHostMediaPreloadStatusNotFound
*/
type V2UpdateHostMediaPreloadStatusNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusNotFound creates V2UpdateHostMediaPreloadStatusNotFound with default headers values
func NewV2UpdateHostMediaPreloadStatusNotFound() *V2UpdateHostMediaPreloadStatusNotFound {

	return &V2UpdateHostMediaPreloadStatusNotFound{}
}

// WithPayload adds the payload to the v2 update host media preload status not found response
func (o *V2UpdateHostMediaPreloadStatusNotFound) WithPayload(payload *models.Error) *V2UpdateHostMediaPreloadStatusNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status not found response
func (o *V2UpdateHostMediaPreloadStatusNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateHostMediaPreloadStatusMethodNotAllowedCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusMethodNotAllowed
const V2UpdateHostMediaPreloadStatusMethodNotAllowedCode int = 405

/*V2UpdateHostMediaPreloadStatusMethodNotAllowed Method Not Allowed.

swagger:response v2UpdateHostMediaPreloadStatusMethodNotAllowed
*/
type V2UpdateHostMediaPreloadStatusMethodNotAllowed struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusMethodNotAllowed creates V2UpdateHostMediaPreloadStatusMethodNotAllowed with default headers values
func NewV2UpdateHostMediaPreloadStatusMethodNotAllowed() *V2UpdateHostMediaPreloadStatusMethodNotAllowed {

	return &V2UpdateHostMediaPreloadStatusMethodNotAllowed{}
}

// WithPayload adds the payload to the v2 update host media preload status method not allowed response
func (o *V2UpdateHostMediaPreloadStatusMethodNotAllowed) WithPayload(payload *models.Error) *V2UpdateHostMediaPreloadStatusMethodNotAllowed {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status method not allowed response
func (o *V2UpdateHostMediaPreloadStatusMethodNotAllowed) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusMethodNotAllowed) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(405)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateHostMediaPreloadStatusConflictCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusConflict
const V2UpdateHostMediaPreloadStatusConflictCode int = 409

/*V2UpdateHostMediaPreloadStatusConflict Error.

swagger:response v2UpdateHostMediaPreloadStatusConflict
*/
type V2UpdateHostMediaPreloadStatusConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusConflict creates V2UpdateHostMediaPreloadStatusConflict with default headers values
func NewV2UpdateHostMediaPreloadStatusConflict() *V2UpdateHostMediaPreloadStatusConflict {

	return &V2UpdateHostMediaPreloadStatusConflict{}
}

// WithPayload adds the payload to the v2 update host media preload status conflict response
func (o *V2UpdateHostMediaPreloadStatusConflict) WithPayload(payload *models.Error) *V2UpdateHostMediaPreloadStatusConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status conflict response
func (o *V2UpdateHostMediaPreloadStatusConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateHostMediaPreloadStatusInternalServerErrorCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusInternalServerError
const V2UpdateHostMediaPreloadStatusInternalServerErrorCode int = 500

/*V2UpdateHostMediaPreloadStatusInternalServerError Error.

swagger:response v2UpdateHostMediaPreloadStatusInternalServerError
*/
type V2UpdateHostMediaPreloadStatusInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusInternalServerError creates V2UpdateHostMediaPreloadStatusInternalServerError with default headers values
func NewV2UpdateHostMediaPreloadStatusInternalServerError() *V2UpdateHostMediaPreloadStatusInternalServerError {

	return &V2UpdateHostMediaPreloadStatusInternalServerError{}
}

// WithPayload adds the payload to the v2 update host media preload status internal server error response
func (o *V2UpdateHostMediaPreloadStatusInternalServerError) WithPayload(payload *models.Error) *V2UpdateHostMediaPreloadStatusInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status internal server error response
func (o *V2UpdateHostMediaPreloadStatusInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateHostMediaPreloadStatusNotImplementedCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusNotImplemented
const V2UpdateHostMediaPreloadStatusNotImplementedCode int = 501

/*V2UpdateHostMediaPreloadStatusNotImplemented Not implemented.

swagger:response v2UpdateHostMediaPreloadStatusNotImplemented
*/
type V2UpdateHostMediaPreloadStatusNotImplemented struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusNotImplemented creates V2UpdateHostMediaPreloadStatusNotImplemented with default headers values
func NewV2UpdateHostMediaPreloadStatusNotImplemented() *V2UpdateHostMediaPreloadStatusNotImplemented {

	return &V2UpdateHostMediaPreloadStatusNotImplemented{}
}

// WithPayload adds the payload to the v2 update host media preload status not implemented response
func (o *V2UpdateHostMediaPreloadStatusNotImplemented) WithPayload(payload *models.Error) *V2UpdateHostMediaPreloadStatusNotImplemented {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status not implemented response
func (o *V2UpdateHostMediaPreloadStatusNotImplemented) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusNotImplemented) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(501)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// V2UpdateHostMediaPreloadStatusServiceUnavailableCode is the HTTP code returned for type V2UpdateHostMediaPreloadStatusServiceUnavailable
const V2UpdateHostMediaPreloadStatusServiceUnavailableCode int = 503

/*V2UpdateHostMediaPreloadStatusServiceUnavailable Unavailable.

swagger:response v2UpdateHostMediaPreloadStatusServiceUnavailable
*/
type V2UpdateHostMediaPreloadStatusServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewV2UpdateHostMediaPreloadStatusServiceUnavailable creates V2UpdateHostMediaPreloadStatusServiceUnavailable with default headers values
func NewV2UpdateHostMediaPreloadStatusServiceUnavailable() *V2UpdateHostMediaPreloadStatusServiceUnavailable {

	return &V2UpdateHostMediaPreloadStatusServiceUnavailable{}
}

// WithPayload adds the payload to the v2 update host media preload status service unavailable response
func (o *V2UpdateHostMediaPreloadStatusServiceUnavailable) WithPayload(payload *models.Error) *V2UpdateHostMediaPreloadStatusServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the v2 update host media preload status service unavailable response
func (o *V2UpdateHostMediaPreloadStatusServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *V2UpdateHostMediaPreloadStatusServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
