// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// V2UpdateHostMediaPreloadStatusReader is a Reader for the V2UpdateHostMediaPreloadStatus structure.
type V2UpdateHostMediaPreloadStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V2UpdateHostMediaPreloadStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewV2UpdateHostMediaPreloadStatusNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewV2UpdateHostMediaPreloadStatusUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV2UpdateHostMediaPreloadStatusForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV2UpdateHostMediaPreloadStatusNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewV2UpdateHostMediaPreloadStatusMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewV2UpdateHostMediaPreloadStatusConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV2UpdateHostMediaPreloadStatusInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewV2UpdateHostMediaPreloadStatusNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewV2UpdateHostMediaPreloadStatusServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV2UpdateHostMediaPreloadStatusNoContent creates a V2UpdateHostMediaPreloadStatusNoContent with default headers values
func NewV2UpdateHostMediaPreloadStatusNoContent() *V2UpdateHostMediaPreloadStatusNoContent {
	return &V2UpdateHostMediaPreloadStatusNoContent{}
}

/* V2UpdateHostMediaPreloadStatusNoContent describes a response with status code 204, with default header values.

Update received
*/
type V2UpdateHostMediaPreloadStatusNoContent struct {
}

func (o *V2UpdateHostMediaPreloadStatusNoContent) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusNoContent ", 204)
}

func (o *V2UpdateHostMediaPreloadStatusNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewV2UpdateHostMediaPreloadStatusUnauthorized creates a V2UpdateHostMediaPreloadStatusUnauthorized with default headers values
func NewV2UpdateHostMediaPreloadStatusUnauthorized() *V2UpdateHostMediaPreloadStatusUnauthorized {
	return &V2UpdateHostMediaPreloadStatusUnauthorized{}
}

/* V2UpdateHostMediaPreloadStatusUnauthorized describes a response with status code 401, with default header values.

Unauthorized.
*/
type V2UpdateHostMediaPreloadStatusUnauthorized struct {
	Payload *models.InfraError
}

func (o *V2UpdateHostMediaPreloadStatusUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusUnauthorized  %+v", 401, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusUnauthorized) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateHostMediaPreloadStatusForbidden creates a V2UpdateHostMediaPreloadStatusForbidden with default headers values
func NewV2UpdateHostMediaPreloadStatusForbidden() *V2UpdateHostMediaPreloadStatusForbidden {
	return &V2UpdateHostMediaPreloadStatusForbidden{}
}

/* V2UpdateHostMediaPreloadStatusForbidden describes a response with status code 403, with default header values.

Forbidden.
*/
type V2UpdateHostMediaPreloadStatusForbidden struct {
	Payload *models.InfraError
}

func (o *V2UpdateHostMediaPreloadStatusForbidden) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusForbidden  %+v", 403, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusForbidden) GetPayload() *models.InfraError {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.InfraError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateHostMediaPreloadStatusNotFound creates a V2UpdateHostMediaPreloadStatusNotFound with default headers values
func NewV2UpdateHostMediaPreloadStatusNotFound() *V2UpdateHostMediaPreloadStatusNotFound {
	return &V2UpdateHostMediaPreloadStatusNotFound{}
}

/* V2UpdateHostMediaPreloadStatusNotFound describes a response with status code 404, with default header values.

Error.
*/
type V2UpdateHostMediaPreloadStatusNotFound struct {
	Payload *models.Error
}

func (o *V2UpdateHostMediaPreloadStatusNotFound) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusNotFound  %+v", 404, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateHostMediaPreloadStatusMethodNotAllowed creates a V2UpdateHostMediaPreloadStatusMethodNotAllowed with default headers values
func NewV2UpdateHostMediaPreloadStatusMethodNotAllowed() *V2UpdateHostMediaPreloadStatusMethodNotAllowed {
	return &V2UpdateHostMediaPreloadStatusMethodNotAllowed{}
}

/* V2UpdateHostMediaPreloadStatusMethodNotAllowed describes a response with status code 405, with default header values.

Method Not Allowed.
*/
type V2UpdateHostMediaPreloadStatusMethodNotAllowed struct {
	Payload *models.Error
}

func (o *V2UpdateHostMediaPreloadStatusMethodNotAllowed) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusMethodNotAllowed  %+v", 405, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusMethodNotAllowed) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateHostMediaPreloadStatusConflict creates a V2UpdateHostMediaPreloadStatusConflict with default headers values
func NewV2UpdateHostMediaPreloadStatusConflict() *V2UpdateHostMediaPreloadStatusConflict {
	return &V2UpdateHostMediaPreloadStatusConflict{}
}

/* V2UpdateHostMediaPreloadStatusConflict describes a response with status code 409, with default header values.

Error.
*/
type V2UpdateHostMediaPreloadStatusConflict struct {
	Payload *models.Error
}

func (o *V2UpdateHostMediaPreloadStatusConflict) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusConflict  %+v", 409, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateHostMediaPreloadStatusInternalServerError creates a V2UpdateHostMediaPreloadStatusInternalServerError with default headers values
func NewV2UpdateHostMediaPreloadStatusInternalServerError() *V2UpdateHostMediaPreloadStatusInternalServerError {
	return &V2UpdateHostMediaPreloadStatusInternalServerError{}
}

/* V2UpdateHostMediaPreloadStatusInternalServerError describes a response with status code 500, with default header values.

Error.
*/
type V2UpdateHostMediaPreloadStatusInternalServerError struct {
	Payload *models.Error
}

func (o *V2UpdateHostMediaPreloadStatusInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusInternalServerError  %+v", 500, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateHostMediaPreloadStatusNotImplemented creates a V2UpdateHostMediaPreloadStatusNotImplemented with default headers values
func NewV2UpdateHostMediaPreloadStatusNotImplemented() *V2UpdateHostMediaPreloadStatusNotImplemented {
	return &V2UpdateHostMediaPreloadStatusNotImplemented{}
}

/* V2UpdateHostMediaPreloadStatusNotImplemented describes a response with status code 501, with default header values.

Not implemented.
*/
type V2UpdateHostMediaPreloadStatusNotImplemented struct {
	Payload *models.Error
}

func (o *V2UpdateHostMediaPreloadStatusNotImplemented) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusNotImplemented  %+v", 501, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusNotImplemented) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV2UpdateHostMediaPreloadStatusServiceUnavailable creates a V2UpdateHostMediaPreloadStatusServiceUnavailable with default headers values
func NewV2UpdateHostMediaPreloadStatusServiceUnavailable() *V2UpdateHostMediaPreloadStatusServiceUnavailable {
	return &V2UpdateHostMediaPreloadStatusServiceUnavailable{}
}

/* V2UpdateHostMediaPreloadStatusServiceUnavailable describes a response with status code 503, with default header values.

Unavailable.
*/
type V2UpdateHostMediaPreloadStatusServiceUnavailable struct {
	Payload *models.Error
}

func (o *V2UpdateHostMediaPreloadStatusServiceUnavailable) Error() string {
	return fmt.Sprintf("[PUT /v2/infra-envs/{infra_env_id}/hosts/{host_id}/media-preload-status][%d] v2UpdateHostMediaPreloadStatusServiceUnavailable  %+v", 503, o.Payload)
}
func (o *V2UpdateHostMediaPreloadStatusServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *V2UpdateHostMediaPreloadStatusServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
