// Code generated by go-swagger; DO NOT EDIT.

package installer

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/openshift/assisted-service/models"
)

// NewV2UpdateHostMediaPreloadStatusParams creates a new V2UpdateHostMediaPreloadStatusParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV2UpdateHostMediaPreloadStatusParams() *V2UpdateHostMediaPreloadStatusParams {
	return &V2UpdateHostMediaPreloadStatusParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV2UpdateHostMediaPreloadStatusParamsWithTimeout creates a new V2UpdateHostMediaPreloadStatusParams object
// with the ability to set a timeout on a request.
func NewV2UpdateHostMediaPreloadStatusParamsWithTimeout(timeout time.Duration) *V2UpdateHostMediaPreloadStatusParams {
	return &V2UpdateHostMediaPreloadStatusParams{
		timeout: timeout,
	}
}

// NewV2UpdateHostMediaPreloadStatusParamsWithContext creates a new V2UpdateHostMediaPreloadStatusParams object
// with the ability to set a context for a request.
func NewV2UpdateHostMediaPreloadStatusParamsWithContext(ctx context.Context) *V2UpdateHostMediaPreloadStatusParams {
	return &V2UpdateHostMediaPreloadStatusParams{
		Context: ctx,
	}
}

// NewV2UpdateHostMediaPreloadStatusParamsWithHTTPClient creates a new V2UpdateHostMediaPreloadStatusParams object
// with the ability to set a custom HTTPClient for a request.
func NewV2UpdateHostMediaPreloadStatusParamsWithHTTPClient(client *http.Client) *V2UpdateHostMediaPreloadStatusParams {
	return &V2UpdateHostMediaPreloadStatusParams{
		HTTPClient: client,
	}
}

/* V2UpdateHostMediaPreloadStatusParams contains all the parameters to send to the API endpoint
   for the v2 update host media preload status operation.

   Typically these are written to a http.Request.
*/
type V2UpdateHostMediaPreloadStatusParams struct {

	/* HostID.

	   The host whose media preload status is being updated.

	   Format: uuid
	*/
	HostID strfmt.UUID

	/* InfraEnvID.

	   The infra-env of the host whose media preload status is being updated.

	   Format: uuid
	*/
	InfraEnvID strfmt.UUID

	/* MediaPreloadStatusParams.

	   Parameters for updating media preload status.
	*/
	MediaPreloadStatusParams *models.MediaPreloadStatusParams

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v2 update host media preload status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2UpdateHostMediaPreloadStatusParams) WithDefaults() *V2UpdateHostMediaPreloadStatusParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v2 update host media preload status params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V2UpdateHostMediaPreloadStatusParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) WithTimeout(timeout time.Duration) *V2UpdateHostMediaPreloadStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) WithContext(ctx context.Context) *V2UpdateHostMediaPreloadStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) WithHTTPClient(client *http.Client) *V2UpdateHostMediaPreloadStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHostID adds the hostID to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) WithHostID(hostID strfmt.UUID) *V2UpdateHostMediaPreloadStatusParams {
	o.SetHostID(hostID)
	return o
}

// SetHostID adds the hostId to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) SetHostID(hostID strfmt.UUID) {
	o.HostID = hostID
}

// WithInfraEnvID adds the infraEnvID to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) WithInfraEnvID(infraEnvID strfmt.UUID) *V2UpdateHostMediaPreloadStatusParams {
	o.SetInfraEnvID(infraEnvID)
	return o
}

// SetInfraEnvID adds the infraEnvId to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) SetInfraEnvID(infraEnvID strfmt.UUID) {
	o.InfraEnvID = infraEnvID
}

// WithMediaPreloadStatusParams adds the mediaPreloadStatusParams to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) WithMediaPreloadStatusParams(mediaPreloadStatusParams *models.MediaPreloadStatusParams) *V2UpdateHostMediaPreloadStatusParams {
	o.SetMediaPreloadStatusParams(mediaPreloadStatusParams)
	return o
}

// SetMediaPreloadStatusParams adds the mediaPreloadStatusParams to the v2 update host media preload status params
func (o *V2UpdateHostMediaPreloadStatusParams) SetMediaPreloadStatusParams(mediaPreloadStatusParams *models.MediaPreloadStatusParams) {
	o.MediaPreloadStatusParams = mediaPreloadStatusParams
}

// WriteToRequest writes these params to a swagger request
func (o *V2UpdateHostMediaPreloadStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param host_id
	if err := r.SetPathParam("host_id", o.HostID.String()); err != nil {
		return err
	}

	// path param infra_env_id
	if err := r.SetPathParam("infra_env_id", o.InfraEnvID.String()); err != nil {
		return err
	}
	if o.MediaPreloadStatusParams != nil {
		if err := r.SetBodyParam(o.MediaPreloadStatusParams); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
