// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MediaPreloadStatusParams media preload status params
//
// swagger:model media-preload-status-params
type MediaPreloadStatusParams struct {

	// The status of media preloading.
	// Required: true
	PreloadStatus *PreloadStatus `json:"preload_status" gorm:"type:varchar(2048)"`
}

// Validate validates this media preload status params
func (m *MediaPreloadStatusParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePreloadStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MediaPreloadStatusParams) validatePreloadStatus(formats strfmt.Registry) error {

	if err := validate.Required("preload_status", "body", m.PreloadStatus); err != nil {
		return err
	}

	if err := validate.Required("preload_status", "body", m.PreloadStatus); err != nil {
		return err
	}

	if m.PreloadStatus != nil {
		if err := m.PreloadStatus.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("preload_status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("preload_status")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this media preload status params based on the context it is used
func (m *MediaPreloadStatusParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePreloadStatus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MediaPreloadStatusParams) contextValidatePreloadStatus(ctx context.Context, formats strfmt.Registry) error {

	if m.PreloadStatus != nil {
		if err := m.PreloadStatus.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("preload_status")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("preload_status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MediaPreloadStatusParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MediaPreloadStatusParams) UnmarshalBinary(b []byte) error {
	var res MediaPreloadStatusParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
